import { z } from "zod";

const BASE_PATH = "https://raw.githubusercontent.com/junobuild/docs/main/docs";

export const TOPICS = {
  intro: "/intro.mdx",
  start_a_new_project: "/start-a-new-project.mdx",
  setup_the_sdk: "/setup-the-sdk.mdx",
  create_a_satellite: "/create-a-satellite.mdx",
  terminology: "/terminology.mdx",
  pricing: "/pricing.md",
  faq: "/faq.md",
  troubleshooting: "/troubleshooting.md",

  build_authentication: "/build/authentication/index.md",
  build_authentication_google: "/build/authentication/google.mdx",
  build_authentication_github: "/build/authentication/github.mdx",
  build_authentication_internet_identity: "/build/authentication/internet-identity.md",
  build_authentication_passkeys: "/build/authentication/passkeys.md",
  build_authentication_management: "/build/authentication/management.md",
  build_authentication_utilities: "/build/authentication/utilities.md",
  build_authentication_dev: "/build/authentication/dev.md",

  build_datastore: "/build/datastore/index.mdx",
  build_datastore_collections: "/build/datastore/collections.md",
  build_datastore_development: "/build/datastore/development.mdx",

  build_storage: "/build/storage/index.mdx",
  build_storage_collections: "/build/storage/collections.md",
  build_storage_development: "/build/storage/development.mdx",

  build_hosting: "/build/hosting/index.md",
  build_hosting_configuration: "/build/hosting/configuration.mdx",
  build_hosting_development: "/build/hosting/development.md",

  build_functions: "/build/functions/index.md",
  build_functions_development: "/build/functions/development/index.mdx",
  build_functions_development_rust: "/build/functions/development/rust.mdx",
  build_functions_development_typescript: "/build/functions/development/typescript.mdx",
  build_functions_lifecycle: "/build/functions/lifecycle.md",
  build_functions_logs: "/build/functions/logs.md",

  build_analytics: "/build/analytics/index.md",
  build_analytics_setup: "/build/analytics/setup.mdx",
  build_analytics_development: "/build/analytics/development.md",

  build_components_analytics: "/build/components/analytics.mdx",
  build_components_apply_configuration: "/build/components/apply_configuration.mdx",
  build_components_assertions: "/build/components/assertions.mdx",
  build_components_certified_reads: "/build/components/certified-reads.md",
  build_components_client_side: "/build/components/client-side.mdx",
  build_components_datastore_storage: "/build/components/datastore-storage.md",
  build_components_encoding: "/build/components/encoding.mdx",
  build_components_http_headers: "/build/components/http-headers.mdx",
  build_components_iframe: "/build/components/iframe.mdx",
  build_components_ignore_files: "/build/components/ignore-files.mdx",
  build_components_nodejs_usage: "/build/components/nodejs-usage.md",
  build_components_precompress: "/build/components/precompress.mdx",
  build_components_redirects: "/build/components/redirects.mdx",
  build_components_rewrites: "/build/components/rewrites.mdx",
  build_components_source: "/build/components/source.mdx",
  build_components_source_examples: "/build/components/source-examples.mdx",

  reference_cli: "/reference/cli.mdx",
  reference_cli_changes: "/reference/cli/changes.md",
  reference_cli_changes_apply: "/reference/cli/changes-apply.md",
  reference_cli_changes_list: "/reference/cli/changes-list.md",
  reference_cli_changes_reject: "/reference/cli/changes-reject.md",
  reference_cli_config: "/reference/cli/config.md",
  reference_cli_config_apply: "/reference/cli/config-apply.md",
  reference_cli_config_init: "/reference/cli/config-init.md",
  reference_cli_emulator: "/reference/cli/emulator.md",
  reference_cli_emulator_start: "/reference/cli/emulator-start.md",
  reference_cli_emulator_wait: "/reference/cli/emulator-wait.md",
  reference_cli_functions: "/reference/cli/functions.md",
  reference_cli_functions_build: "/reference/cli/functions-build.md",
  reference_cli_functions_changes: "/reference/cli/functions-changes.md",
  reference_cli_functions_eject: "/reference/cli/functions-eject.md",
  reference_cli_functions_publish: "/reference/cli/functions-publish.md",
  reference_cli_functions_upgrade: "/reference/cli/functions-upgrade.md",
  reference_cli_hosting: "/reference/cli/hosting.md",
  reference_cli_hosting_clear: "/reference/cli/hosting-clear.md",
  reference_cli_hosting_deploy: "/reference/cli/hosting-deploy.md",
  reference_cli_hosting_prune: "/reference/cli/hosting-prune.md",
  reference_cli_login: "/reference/cli/login.md",
  reference_cli_logout: "/reference/cli/logout.md",
  reference_cli_open: "/reference/cli/open.md",
  reference_cli_run: "/reference/cli/run.md",
  reference_cli_snapshot: "/reference/cli/snapshot.md",
  reference_cli_snapshot_upload: "/reference/cli/snapshot-upload.md",
  reference_cli_start: "/reference/cli/start.md",
  reference_cli_status: "/reference/cli/status.md",
  reference_cli_stop: "/reference/cli/stop.md",
  reference_cli_upgrade: "/reference/cli/upgrade.md",
  reference_cli_version: "/reference/cli/version.md",
  reference_cli_whoami: "/reference/cli/whoami.md",

  reference_emulator: "/reference/emulator/infrastructure.md",
  reference_emulator_satellite: "/reference/emulator/satellite.md",
  reference_emulator_skylab: "/reference/emulator/skylab.md",

  reference_functions: "/reference/functions/components/ic-cdk.md",
  reference_functions_sdk: "/reference/functions/components/sdk.mdx",
  reference_functions_utils: "/reference/functions/components/utils.md",
  reference_functions_rust: "/reference/functions/rust/ic-cdk.mdx",
  reference_functions_rust_sdk: "/reference/functions/rust/sdk.mdx",
  reference_functions_rust_utils: "/reference/functions/rust/utils.mdx",
  reference_functions_rust_crate_versions: "/reference/functions/rust/crate-versions.md",
  reference_functions_typescript: "/reference/functions/typescript/ic-cdk.mdx",
  reference_functions_typescript_sdk: "/reference/functions/typescript/sdk.mdx",
  reference_functions_typescript_utils: "/reference/functions/typescript/utils.mdx",
  reference_functions_typescript_canisters: "/reference/functions/typescript/canisters.mdx",
  reference_functions_typescript_schema: "/reference/functions/typescript/schema.md",
  reference_functions_typescript_node: "/reference/functions/typescript/node.md",

  reference_configuration: "/reference/configuration.mdx",
  reference_settings: "/reference/settings.md",
  reference_plugins: "/reference/plugins.mdx",

  guides_local_development: "/guides/local-development.mdx",
  guides_manual_deployment: "/guides/manual-deployment.mdx",
  guides_e2e: "/guides/e2e.md",
  guides_ai: "/guides/ai.md",
  guides_typescript: "/guides/typescript.mdx",
  guides_nodejs: "/guides/nodejs.mdx",
  guides_rust: "/guides/rust.mdx",
  guides_github_actions: "/guides/github-actions/index.mdx",
  guides_github_actions_deploy_frontend: "/guides/github-actions/deploy-frontend.mdx",
  guides_github_actions_publish_functions: "/guides/github-actions/publish-functions.mdx",
  guides_github_actions_upgrade_functions: "/guides/github-actions/upgrade-functions.mdx",
  guides_react: "/guides/react/build.mdx",
  guides_react_deploy: "/guides/react/deploy.mdx",
  guides_nextjs: "/guides/nextjs/build.mdx",
  guides_nextjs_deploy: "/guides/nextjs/deploy.mdx",
  guides_angular: "/guides/angular/build.mdx",
  guides_angular_deploy: "/guides/angular/deploy.mdx",
  guides_astro: "/guides/astro/build.mdx",
  guides_astro_deploy: "/guides/astro/deploy.mdx",
  guides_sveltekit: "/guides/sveltekit/build.mdx",
  guides_sveltekit_deploy: "/guides/sveltekit/deploy.mdx",
  guides_vue: "/guides/vue/build.mdx",
  guides_vue_deploy: "/guides/vue/deploy.mdx",
  guides_docusaurus: "/guides/docusaurus/deploy.mdx",

  management_monitoring: "/management/monitoring.md",
  management_snapshots: "/management/snapshots.md",

  miscellaneous_access_keys: "/miscellaneous/access-keys.md",
  miscellaneous_architecture: "/miscellaneous/architecture.md",
  miscellaneous_best_practices: "/miscellaneous/best-practices.md",
  miscellaneous_infrastructure: "/miscellaneous/infrastructure.md",
  miscellaneous_memory: "/miscellaneous/memory.md",
  miscellaneous_wallet: "/miscellaneous/wallet.mdx",
  miscellaneous_workarounds: "/miscellaneous/workarounds.md",
  miscellaneous_provisioning_options: "/miscellaneous/provisioning-options.mdx",

  comparison_vs_heroku: "/comparison/vs-heroku.md",
  comparison_vs_netlify: "/comparison/vs-netlify.md",
  comparison_vs_railway: "/comparison/vs-railway.md",
  comparison_vs_self_hosting: "/comparison/vs-self-hosting.md",
  comparison_vs_vercel: "/comparison/vs-vercel.md",

  components_core: "/components/core.mdx",
  components_bash: "/components/bash.mdx",
  components_cycles: "/components/cycles.md",
  components_subnets: "/components/subnets.md",

  examples_frontend_react_typescript: "/examples/frontend/react-typescript.mdx",
  examples_frontend_react_javascript: "/examples/frontend/react-javascript.mdx",
  examples_frontend_nextjs: "/examples/frontend/nextjs.mdx",
  examples_frontend_angular: "/examples/frontend/angular.mdx",
  examples_frontend_sveltekit: "/examples/frontend/sveltekit.mdx",
  examples_frontend_vue: "/examples/frontend/vue.mdx",
  examples_frontend_vanilla_javascript: "/examples/frontend/vanilla-javascript.mdx",
  examples_functions_rust: "/examples/functions/rust/assertion.mdx",
  examples_functions_rust_canister_calls: "/examples/functions/rust/canister-calls.mdx",
  examples_functions_rust_generating_assets: "/examples/functions/rust/generating-assets.mdx",
  examples_functions_rust_mutating_docs: "/examples/functions/rust/mutating-docs.mdx",
  examples_functions_typescript: "/examples/functions/typescript/assertion.mdx",
  examples_functions_typescript_canister_calls: "/examples/functions/typescript/canister-calls.mdx",
  examples_functions_typescript_mutating_docs: "/examples/functions/typescript/mutating-docs.mdx"
} as const;

export type TopicKey = keyof typeof TOPICS;

export const junoDocsSchema = z
  .object({
    topic: z
      .enum(Object.keys(TOPICS) as [TopicKey, ...TopicKey[]])
      .describe(
        "Documentation topic to retrieve. Full Juno docs from GitHub repo: https://github.com/junobuild/docs/tree/main/docs"
      )
  })
  .strict();
